import Header from "@/components/Layout/Header";
import "./globals.css";
import Hero from "@/components/Hero";
import Footer from "@/components/Layout/Footer";

// Comment goes here

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <Header />
        <Hero />
        {children}
        <Footer />
      </body>
    </html>
  );
}


